ALTER TABLE `quest_template` DROP COLUMN `RewardArenaPoints`;
ALTER TABLE `access_requirement` DROP COLUMN `completed_achievement`;
ALTER TABLE `creature_template` DROP COLUMN `difficulty_entry_1`,`difficulty_entry_2`,`difficulty_entry_3`;
DROP TABLE IF EXISTS `player_factionchange_achievement`;
DROP TABLE IF EXISTS `player_factionchange_items`;
DROP TABLE IF EXISTS `player_factionchange_reputations`;
DROP TABLE IF EXISTS `player_factionchange_spells`;
DELETE FROM `player_classlevelstats` WHERE `level`>60;
DELETE FROM `player_levelstats` WHERE `level`>60 or `race`>9;
DELETE FROM `playercreateinfo` WHERE `race`>9;
DELETE FROM `playercreateinfo_action` WHERE `race`>9;
DELETE FROM `playercreateinfo_item` WHERE `race`>9;
DELETE FROM `playercreateinfo_spell` WHERE `race`>9;
DELETE FROM `playercreateinfo_spell_custom` WHERE `race`>9;
UPDATE trinity_string SET content_default="Found items %u: %u ( inventory %u mail %u auction %u)" WHERE entry=438; -- Remove 'guild %u'
DROP TABLE IF EXISTS `prospecting_loot_template`;
DROP TABLE IF EXISTS `skill_extra_item_template`;
DROP TABLE IF EXISTS `skill_discovery_template`;
ALTER TABLE creature_template DROP COLUMN heroic_entry;
ALTER TABLE access_requirement DROP COLUMN heroic_key;
ALTER TABLE access_requirement DROP COLUMN heroic_key2;
ALTER TABLE access_requirement DROP COLUMN heroic_quest_done;
ALTER TABLE access_requirement DROP COLUMN heroic_quest_failed_text;
ALTER TABLE item_template DROP COLUMN socketColor_1;
ALTER TABLE item_template DROP COLUMN socketContent_1;
ALTER TABLE item_template DROP COLUMN socketColor_2;
ALTER TABLE item_template DROP COLUMN socketContent_2;
ALTER TABLE item_template DROP COLUMN socketColor_3;
ALTER TABLE item_template DROP COLUMN socketContent_3;
ALTER TABLE item_template DROP COLUMN socketBonus;
ALTER TABLE item_template DROP COLUMN GemProperties;
ALTER TABLE item_template DROP COLUMN TotemCategory;
ALTER TABLE creature DROP COLUMN spawnMask;
ALTER TABLE gameobject DROP COLUMN spawnMask;
